### ISSUE TITLE
Build gebrochen -> PrivateFieldFoobar fehlt

### ISSUE THREAD

**Issue by Petikoch** [ReactiveMeetupLucerne/SpringWebFluxWithSpringBoot2.0#2]
Hoi @synox ,

kannst Du die Klasse noch adden? Der Build ist momentan gebrochen...

Danke & Gruss,
Peti

**Comment by Petikoch** [comment]
@synox habe die gebrochenen Codestellen kurzerhand einfach provisorisch auskommentiert

**Comment by Petikoch** [comment]
Betreffend "Question 1": Ich glaube, die Klasse muss nicht Serializable implementieren... Jackson muss das Ding einfach "irgendwie" handlen können.

So viel ich weiss, funktionieren out of the box diejenigen Klassen, die der JavaBean Convention folgen (== default constructor, getter + setter). Man kann aber auch immutable Klassen verwenden, da braucht Jackson einfach etwas Hilfe. Siehe zB die neue TextDto.java Klasse.

**Comment by synox** [comment]
Opps, danke für den Hinweis!
